driver:
  name: MACE
  model_path: path_to_model/MACE-omol-0-extra-large-1024.model
  device: null        # cuda or cpu, default auto-detect
  precision: float64  # float32 or float64
  model_type: omol    # model type for MACE, (omol or mp)
  dispersion: false   # whether to include dispersion correction
  dispersion_xc: pbe  # dispersion for certain xc functionals
  damping: bj         # damping type for dispersion correction
  head: null          # for mace-mh