inputfile: reaction_pair.xyz
charge: 0
multiplicity: 1

driver:
  # Any qc_launcher driver that can provide energies and forces can be used.
  name: pyscf
  xc: B3LYP
  basis: def2-SVP
  with_df: false
  with_gpu: false

gsm:
  gsm_type: DE_GSM
  num_nodes: 9
  coordinate_type: DLC
  optimizer_method: eigenvector_follow
  line_search: NoLineSearch
  climb: true
  fmax: 0.05
  dmax: 0.1
  max_gsm_steps: 64
  max_opt_steps: 3
  fixed_reactant: false
  fixed_product: false
  clear_scratch: false
